name: Build project and Run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: wasm build
        run: |
          cd wasm
          cargo install wasm-pack
          wasm-pack build --out-dir ../pkg
      - name: npm install, build
        env: 
          CI: false
        run: |
          cd client
          rm -rf node_modules
          npm cache clean -f
          npm install && npm install -g @lhci/cli@0.6.x
          npm run build
      - name: run Lighthouse CI
        run: lhci autorun --upload.target=temporary-public-storage --staticDistDir=./build || echo "LHCI failed!"
